config/routes.rb
Rails.application.routes.draw do

  resources :application 
  resources :images 
 
  # upvote route to action
  get '/images/:id/upvote' => 'images#create_upvote'
  post '/images/:id/upvote' => 'images#create_upvote', as: 'upvote'
  
  root to: 'images#index'

  delete '/sessions' => 'sessions#destroy', as: 'logout'
  resources :sessions, only: [:new, :create, :destroy]
  resources :comments
  resources :users, only: [:index, :new, :create, :show]
  
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :image
  belongs_to :user
end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :user
	has_attached_file :avatar, 
    :styles => { :medium => "700x700>", :thumb => "100x100>" }, 
    :default_url => "/images/:style/missing.png"

	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  validates_presence_of :photo, :title, :date, :description, :link
  
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  has_many :images

  validates_uniqueness_of :username, :email
  validates_presence_of :username, :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  def current_user
    User.where(id: session["user_id"]).first
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def new
		@comment = Comment.new
	end
	def create
		@comment = Comment.new(comment_params)
		if @comment.save
			redirect_to image_path(@comment.image)
		end
	end
	def edit
		@comment = Comment.find(params[:id])
	end
	def update
		@comment = Comment.find(params[:id])
		if @comment.update_attributes(comment_params)
			redirect_to image_path(@comment.image_id)
		end
	end

	private

  def comment_params
    params.require(:comment).permit(:body, :user_id, :image_id)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def index
    @images = Image.order(votes: :desc)
    @comment=Comment.new
    @commentsSubmitted = Comment.where(image_id: params[:id])
    @topUsers= User.order("vote_count DESC").limit(5)
  end
  
  def show
    @image = Image.find(params[:id])
    @comment=Comment.new
    @commentsSubmitted = Comment.where(image_id: params[:id])
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    # raise params.inspect
    @image.avatar=URI.parse(params[:image][:photo])
    if @image.save
      flash[:image_success] = "Upload Successful"
      redirect_to images_path
    else
      flash[:image_error] = "All fields must be complete"
      redirect_to images_path
    end
  end
  
  def create_upvote
    @image = Image.find(params[:id])
    user=@image.user
    if @image['votes'].include?(current_user.id)
      @image['votes'].delete(current_user.id)
      @image.save
      user.vote_count-=1
      user.save
      redirect_to image_path(@image.id)
    else
      @image['votes'] << current_user.id
      @image.save
      user.vote_count+=1
      user.save
      redirect_to image_path(@image.id)
    end
  end
  
  private

  def image_params
    params.require(:image).permit(:title, :description, :link, :date, :photo, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
    if params[:user_created] == 'true'
      @user_created_message = 'User successfully created!'
    end
  end

  def create
    u = User.where(email: params[:user][:email]).first 
    if u !=nil && u.authenticate(params[:user][:password])
      session['user_id'] = u.id.to_s 
      flash[:success] = "Successfully Signed In"
      redirect_to images_path
    end
  end

  def destroy
    session.destroy
    redirect_to images_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
    @user = User.new
	end

  def create
    user = User.new(params.require(:user).permit(:email, :username, :password)) 
    if user.save
      session['user_id'] = user.id.to_s
      flash[:success] = "Welcome to our app" 
      redirect_to root_path
    else
      flash[:error] = "Username and/or Email already registered"
      redirect_to root_path
    end
  end

  def show
    @user = User.where(id: session['user_id']).first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/edit.html.erb
<h1>Edit my comment</h1>
<%= form_for @comment do |f| %>
	<%= f.text_area :body %>
	<br />
	<%= f.hidden_field :user_id, :value => current_user.id %>
	<%= f.hidden_field :image_id, :value => params[:image_id] %>
	<%= f.submit 'Edit your comment' %>
<% end %>

app/views/images/index.html.erb
<% if flash[:success] || flash[:image_success] || flash[:error] %>
  <div class='flash'>
    <%= flash[:success] %> 
    <%= flash[:image_success] %>
    <%= flash[:error] %>
  </div>
<% end %>

<section class='main'>
  <% @images.each do |i| %>
    <%= link_to image_path(i.id) do %>
      <div class='thumb'>
         <%= image_tag i.avatar.url(:medium) %>
        <div class='txthover' >
          <%= i.title %>
          <br>
          <br>
          <strong> <%= i.votes.count %> </strong> <i class="fa fa-heart"></i>
        </div>
      </div>
    <% end %>
  <% end %>
</section>

app/views/images/show.html.erb
<section class='show'>
  <div class='right'>
  <!-- <img src="<%#= @image.photo %>"> -->
  <%= image_tag @image.avatar.url(:medium) %>
  </div>
  <div class='left'>
  <div class='content'>
    <h3>Title: <%= @image.title %> </h3>
    <h3>Posted By: <%=@image.user.username %></h3>
    <h3>Date: <%= @image.date.strftime("%m/%d/%Y") %></h3>
    <h3> Worldview URL: <a href=<%=@image.link%> target="_blank"> Click Here! </a> </h3>
    <br>
    <h3>Description: <%= @image.description %></h3>
    <br>
      <span class='likes'>
      <% if current_user %>
        <% if @image.votes.include? current_user.id %>
          <h3><%= @image.votes.count %>
<%= link_to upvote_path do %><i class="fa fa-heart"></i> </h3><% end %>
        <% else %>
          <h3><%= @image.votes.count %><%= link_to upvote_path do %><i class="fa fa-heart-o"></i></h3><% end %>
        <% end %>
      <% else %>
        <h3> Login To <i class="fa fa-heart"></i> </h3>
      <% end %>
      </span>
    <br>
    <% if current_user %>
      <div class='addComment'>
      	<%= form_for @comment, :url =>{:controller =>"comments", :action =>"create"} do |f| %>
    	  	<%= f.text_area :body, placeholder: "Add your comment here" %>
          <% if current_user %>
      	  	<%= f.hidden_field :user_id, :value => current_user.id %>
      	  	<%= f.hidden_field :image_id, :value => params[:id] %> 
          <% end %>
          <br>
      		<%= f.submit 'Add your comment' %>
      	<% end %>
      </div>
    <% else %>
    <h3 style='color:red'> Login to add comments </h3>
    <% end %>
      <hr >
      <div class='commentSection'>
        <h1>Comments</h1>
      	<% @commentsSubmitted.each do |comment| %>
        <div class='comment'>
          <strong><%= comment.user.username %> said:</strong><br />
      		<%= comment.body %>
          <% if current_user %>
      			<% if current_user.id == comment.user_id %>
      			 (<%= link_to 'Edit', edit_comment_path(comment, image_id: params[:id]) %>)
      			<% end %>
          <% end %>
      		<br />
        </div>
      	<% end %>
      </div>
    </div>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Catsinspace</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
</head>
<body>
  <i class="fa fa-bars menu"></i>
  <div class='navigation'>
    <%= button_to "HOME", root_path, :class => 'session', method: :get %>
    <% if current_user != nil %>
     <div class='session'>
      <button class='postbutton'> Post </button>
      </div>
      <%= button_to "Log out", sessions_path, :class => 'session', method: :delete %>
      <% else %>
      <div class='session'>
        <button class='signupbutton'> sign up</button>
      </div>
      <div class='session'>
        <button class='loginbutton'> Login </button>
      </div>
    <% end %>
     <div class='session'>
        <button class='instructionbutton'> Instruction </button>
      </div>
    <div class='close'>
      <i class="fa fa-times-circle"></i>
    </div>
  </div>
  
  <div class='forms post hidden'>
    <%= form_for Image.new() do |f| %>
      <h2> title </h2>
      <%= f.text_field :title %>
      <h2> photo </h2>
      <%= f.text_field :photo %>
      <h2> url </h2>
      <%= f.text_field :link %>
      <h2> date </h2>
      <%= f.date_field :date %>
      <h2> description </h2>
      <%= f.text_area :description %>
      <% if current_user %>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <% end %>
      <br>
      <br>

      <%= f.submit "POST", :class => 'submit' %>
    <% end %>
    <br>
    <button class='cancel' style='width:20%'> CANCEL </button>
</div>
<div class='forms login hidden'>
<%= form_for User.new, :url => { :controller => "sessions", :action => "create" } do |f| %> <!-- See the comment under the f.submit line for details. the url tells it to go to the sessions path, create method instead-->
    <h2> E-mail </h2>
     <%= f.text_field :email %><br />
    <h2> Password </h2>
    <%= f.password_field :password %><br />
    <br>
    <%=f.submit 'Log yourself in', :class => 'submit'%> <!-- This will post back to the users controller by default because it's a user. We need to override this behavior -->
    <% end %>
    <br>
    <button class='cancellogin' style='width:20%'> CANCEL </button>
</div>

<div class='forms signup hidden'>
  <%= form_for User.new() do |f|%>
    <h2> Username </h2>
    <%= f.text_field :username %>
    <h2> E-mail </h2>
     <%= f.text_field :email %>
    <h2> Password </h2>
     <%= f.password_field :password %>
    <h2> Password confirmation </h2>
    <%= f.password_field :password_confirmation %>
    <br>
    <br>
    <%=f.submit "Sign In", :class=>'submit' %>
    <br>
    <br>
    <button class='cancelsignup' style='width:20%'> CANCEL </button>

<% end %>
</div>

<div class='leaderboard'>
  <h3>Top 5 Most <i class="fa fa-heart"></i> users</h3>
  <% User.order("vote_count DESC").limit(5).each do |topUser|%>
    <%= topUser.username %> | <%= topUser.vote_count %> <i class="fa fa-heart"></i><br />
  <% end %>
  <div class='closeleader' style='text-align:center;'>
    <i class="fa fa-times-circle"></i>
  </div>
</div>
<br>
<div class='leaderboardbutton'>
  <h3> LEADERBOARD </h3>
</div>
<div class='instruction hidden'>
  <%= image_tag("instructionsv2.png") %>
  <div class='closeinstruction' style='text-align:center;'>
    <i class="fa fa-times-circle"></i>
  </div>
</div>
<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign up!</h1>

<%= form_for @user do |f|%>
    Username: <%= f.text_field :username %><br />
    E-mail: <%= f.text_field :email %><br />
    Password: <%= f.password_field :password %><br />
    Password confirmation: <%= f.password_field :password_confirmation %><br />
 		<%=f.submit %>

<% end %>

app/views/users/show.html.erb
<h1>Welcome to your user page <%= @user.username%> !</h1>
<p>You are now logged in.</p>
<p>E-mail:</p>
<%= @user.email %>